<?xml version="1.0"?>
<robot name="cyber_truck_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Parameters -->
  <xacro:property name="body_length" value="1.2" />
  <xacro:property name="body_width" value="0.6" />
  <xacro:property name="body_height" value="0.3" />
  <xacro:property name="wheel_radius" value="0.15" />
  <xacro:property name="wheel_width" value="0.05" />

  <!-- Material -->
  <material name="silver">
    <color rgba="0.75 0.75 0.75 1" />
  </material>

  <!-- Base Footprint -->
  <link name="base_footprint"/>

  <!-- Body -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}" />
      </geometry>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0" />
      <material name="silver"/>
    </visual>
  </link>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin xyz="${x} ${y} ${z}" rpy="${pi / 2} 0 0" />
        <material name="silver" />
      </visual>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link" />
      <child link="${name}" />
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <!-- All 4 wheels -->
  <xacro:wheel name="front_left_wheel"  x="${body_length/2 - 0.15}" y="${ body_width/2 + 0.01}" z="0" />
  <xacro:wheel name="front_right_wheel" x="${body_length/2 - 0.15}" y="-${body_width/2 + 0.01}" z="0" />
  <xacro:wheel name="rear_left_wheel"   x="-${body_length/2 + 0.15}" y="${ body_width/2 + 0.01}" z="0" />
  <xacro:wheel name="rear_right_wheel"  x="-${body_length/2 + 0.15}" y="-${body_width/2 + 0.01}" z="0" />

  <!-- Joint for base_link to base_footprint -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
